#!/usr/bin/env python3.5
# -*- coding: utf-8 -*-

__author__ = 'Markus Liu'

import redis
import time
import uuid

print('start')
conn=redis.StrictRedis(host='localhost', port=6379, db=0)
conn.flushdb()